### ISSUE TITLE
cannot disable the add on, the hotkey does not work

### ISSUE THREAD

**Issue by sroka-m** [hgiesel/anki_frozen_fields#2]
hello! 
Thank you so much for you add-on! The  things that I am about to mention does not really bother me, but still i am reporting, maybe you wish to look at them some time.  I am on windows and i use Anki 2.1.35. 
When i disable the add-on while one of the fields is frozen, (and restart the anki, of course), the field keeps its "frozen" properties. The snowflakes signs disappear, but the field that i have just filled in, propagates to the next note. (to clarify after I disable the add-on the frozen field is empty, but its content propagates once i fill it in)  I only noticed it by accident. Of course if i enable the add-on back, and unfreeze all fields manually, and disable the add on, no filed is  frozen. 
also the shortcuts do not work, both f9 and shift + f9 opens start menu on my laptop (?!), again I am not complaining , i just found that out because I wanted to see,if the issue above can be fixed by using shortcuts. And by the way, I disabled all my other addons so it does not seem it is due to add-on conflict. Have a lovely day!
Mag

**Comment by hgiesel** [comment]
The functionality of frozen fields, actually uses Ankis built-in feature of "sticky" fields. You can choose to make a field sticky, if you're in the note editor, you select "Fields...", and then each field has the option "Remember last input when adding". This is what frozen fields is built upon. It makes it easier to set this option.

You can set the shortcuts manually, if you go to the "Tools > Add-ons... > Ze Frozen Fields > Config". The choice of the shortcuts is mostly historical.

**Comment by sroka-m** [comment]
Dear Mr. Henrik, 
Thank you for your time and your fantastic explanation! I am really sorry because I essentially accused you add-on for bugs. I hope you forgive my total ignorance. Glutamine does mention stickly fields but he does not say: hej, functionality of this add-on can be achieved by going to fields> “Remember last input when adding” and I’ve just never noticed this feature. With the shortcuts, it is something to do with my laptop, I guess it would work fine if I had normal-size keyboard, I have problem with f shortcuts, e.g. Blender, so I should have suspected that. I changed the hotkeys and it works perfect. 
Thank you once again, 
Mag
