### ISSUE TITLE
How does "ze frozen fields" work on Anki 2.1.45?

### ISSUE THREAD

**Issue by johnnyjohnjohnjohn** [hgiesel/anki_frozen_fields#5]
I was told by creator that this feature would be automatically installed in 2.1.45. I had 2.1.44 which was not compatible with Ze Frozen Fields. So I upgraded expecting to see it embedded into the default functioning of the app. However, this is not the case. How do I reactivate Ze Frozen Fields? Thank you.

**Comment by hgiesel** [comment]
On the upper right corner of the field there is a clickable icon:

<img width="388" alt="Screenshot 2021-08-31 at 13 26 09" src="https://user-images.githubusercontent.com/7188844/131494570-d8efc754-77d3-47c9-bb01-302c6a95e80c.png">
